### ISSUE TITLE
[bug-website module] Kissmanga is not working

### ISSUE THREAD

**Issue by L3L0UCH** [dazedcat19/FMD2#14]
The manga info works alongside the chapter list but downloading fails for some reason. I think this is because of the captcha for each chapters but I have no clue how to solve it. It's been like that for me around 2.0.7.0 and even now with the update.

Also, adding cookies+useragent on advanced settings doesn't work as well.

**Comment by dazedcat19** [comment]
Post the manga, chapter and the log. Also attach the page source.

**Comment by HiP1** [comment]
kissmanga still working for me with converter and default install.

**Comment by HiP1** [comment]
today, it doesn't work for me anymore too.
i get the recaptcha challenge in the log : 
05:48:04:626 WebsitBypass[clounflare]: detected reCapthca challenge, not supported right now. can be redirected to third party capthca solver in the future

i tried to do it on my browser, and use the same user agent, but didn't work.
and in the cookie, there is nothing that points to it.

**Comment by HiP1** [comment]
seems the captcha check is confirmed in the url. i get this in the URL :

?__cf_chl_captcha_tk__=ed9d676d6eb3408e48e418e5c32683ae91126d04-1591187636-0-ASL755i-1jq5WYbJD2XX39EtaYq9xOWuMzKJrU4EafCNZZqHWXMUHc_W8F2pM72LOgEoXdjpkWBgaT0DfhrLRceZYQNnupdlWSTLoER-d2W4hISLAxlmK33RzLGbfv-tvI0uPCIYCuPfanM8K6YMu92cEHnEgLF0DJ2wlMTHL9_Jv_fZIms2R0cABWmvXBx245tR1ZoUoRHUruVdpWyxy5s5JVfKBHzLRui3RjngRFFDJZglf55NZkfBnJ5ey7nbP2z0KSiXV4MMfVSpM1DIr3CEUAL4qUmOsN0KiG3ZJlwqcNnQbTheOtMcbwrQPuAXDOBKcLmO7qFQ_abi8hFI8eeWeCFrEB1WQdouv1P99ofHRskLWgKLVJc3mHSdWWMe4xEF9pU8QwrSG0VwbeP8s0c-5nRl2hTnVX-pCxxa6vl7gTRT5XtW4CmyZ8R4HBGY7mZO5PTSTEMbPlIZ48W-qMDTEKKpX7ULnwepdhYE4nGjW6Eccj9Jjn1mxO_rNuFOR1F4uCXWTlZvOcYxITs5pdoWA_q3PzlYvOITSOuDdzHQ

tried to put it in the cookie, alone or with the rest of the usual cookie workaround, didn't work.
from what is written on the site on the captcha page, it might be because cloudfare or the site thinks we are a robot, i guess for using FMD.

**Comment by Slasar41** [comment]
Currently KissManga put a captcha. Here's the FMD log:
`02.05.06.986 WebsitBypass[clounflare]: detected reCapthca challenge, not supported right now. can be redirected to third party capthca solver in the future`
I've to use cookies workaround and then it'll works fine.
![image](https://user-images.githubusercontent.com/28888646/83678571-280b4d80-a608-11ea-92a0-df06f8aee17b.png)

**Comment by HiP1** [comment]
@Slasar41 what part of the cookie did you use ?

**Comment by Slasar41** [comment]
@HiP1 I just copy the cookies from the main page. Looks like this: `fullListMode=true; __cfduid=d13db2f6fd86176bdf79a4bbcbd9edb201590176997; cf_clearance=b5b74cd4efa5b948eea2ca67317955d739b2fda0-1591211009-0-250; idtz=116.206.28.30-20623095`

**Comment by HiP1** [comment]
@Slasar41 yeah. but kissmanga was known to be very specific with the cookie variable that we use.
seems that now, they need specifically the cfduid, cf_clearance and idtz.
i tried with just those 3 and it worked.
i tried again with the previous cookie setup i used that failed, and it worked too. so maybe they changed something on their end

**Comment by user1705** [comment]
seems to be working fine now that Capcha challenges is no longer on the site.

**Comment by Slasar41** [comment]
I can confirm it's working fine now.

**Comment by dazedcat19** [comment]
seems to be a season where they force for a captcha. maybe regular periodic event. or just depends on the number of ddos attacks.
