### ISSUE TITLE
[website module request] Madokami

### ISSUE THREAD

**Issue by mooglestiltzkin** [dazedcat19/FMD2#158]
**Website Information**
* **Name:**  Madokami
* **Root URL:** https://manga.madokami.al/

In the original FMD1 which FMD2 is supposed to replace, there already is Madokami support.

So why ask? because FMD1 is being discontinued
https://github.com/fmd-project-team/FMD/issues/1145

plz add madokami support to fmd2 :(

**Comment by mastafrooper** [comment]
Pretty sure this was addressed in Issue #25. 

@dazedcat19 needs a user account to be able to access the site to write a module.

**Comment by amit34521** [comment]
I have madokami account and am willing to provide that for this plugin

**Comment by alzamer2** [comment]
hi, @dazedcat19
i plan to write lue file to add madakami to FMD2
as i have account and know some coding
can you tell me what you need and what names of function that you need them to work with fmd and type of return value the program need

ps: ik its double posting, but i'm not sure you will get #25 msg because its closed issue

**Comment by Slasar41** [comment]
@alzamer2 You better join Discord server and ask it there: https://discord.gg/cXKKgw3
