### ISSUE TITLE
[bug] converter.exe didn't transfer all options

### ISSUE THREAD

**Issue by throw395583** [dazedcat19/FMD2#28]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 64 bit

**Describe the bug**
I used the converter.exe to transfer favourites/etc. In Options->Websites->Mangadex section, the "show scanlation group" option didn't transfer. Most other options did, from what I checked.

**Comment by dazedcat19** [comment]
Yes, they're not. because the modules changed drastically. it simply incompatible. I also changed some of the key in mangadex options. so the old settings is useless anyway. the  idea of the website modules is like a plugin. So fmd shouldn't memorize them.
because the website options is only a few, I don't really pay much attention to it. User can easily set it back in no time. Maybe I can put the message in the download section regarding this issue.
