### ISSUE TITLE
[bug] Mangadex failed to download chapter 

### ISSUE THREAD

**Issue by frerouche** [dazedcat19/FMD2#303]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10

**Describe the bug**
Trying to download Useless Ponko chapter 48 fails and returns these errors in the log;

17:53:06:756 TTaskThread, checkforfinish failed=23/23 [MangaDex] "Useless Ponko" > "/chapter/1193134"
17:53:06:756 TTaskThread, download failed. "Useless Ponko" "Useless Ponko - Vol. 07 Ch. 048 - Ping Pong Ponko [Cyan Steam]" "/chapter/1193134"

**Additional context**
The chapter loads fine in firefox without any issues.

**Comment by frerouche** [comment]
Seems to have fixed itself over time as it just succeeded downloading.

**Comment by frerouche** [comment]
Getting these errors again for another manga. It will likely resolve itself on its own like it did the other day.
But I'd like to know the cause for the checkforfinish error?

**Comment by Slasar41** [comment]
By reading this [thread](https://mangadex.org/thread/414205), MangaDex is still recovering so some errors when downloading are expected.
I'm not sure with that error too.

**Comment by Geese1** [comment]
> By reading this [thread](https://mangadex.org/thread/414205), MangaDex is still recovering so some errors when downloading are expected.
> I'm not sure with that error too.

I'm betting these server issues are what's causing chapters I'm watching not to show up when they appear in MangaDex. Over the last few days I've been having issues where chapters will show up on MangaDex, but not in the downloader, even though everything is updated. They will eventually be pushed to the downloader, but it's often hours before they're available. 

Came here looking to see if anyone else has been having this issue, and saw this thread. I can only assume this is caused by the server issues you referenced.

**Comment by Ramdhani04** [comment]
> 
> I'm betting these server issues are what's causing chapters I'm watching not to show up when they appear in MangaDex. Over the last few days I've been having issues where chapters will show up on MangaDex, but not in the downloader, even though everything is updated. They will eventually be pushed to the downloader, but it's often hours before they're available.
> 
> Came here looking to see if anyone else has been having this issue, and saw this thread. I can only assume this is caused by the server issues you referenced.

I also have the same problem
I thought it was just me.....

**Comment by arbiter9605** [comment]
> 
> 
> > By reading this [thread](https://mangadex.org/thread/414205), MangaDex is still recovering so some errors when downloading are expected.
> > I'm not sure with that error too.
> 
> I'm betting these server issues are what's causing chapters I'm watching not to show up when they appear in MangaDex. Over the last few days I've been having issues where chapters will show up on MangaDex, but not in the downloader, even though everything is updated. They will eventually be pushed to the downloader, but it's often hours before they're available.
> 
> Came here looking to see if anyone else has been having this issue, and saw this thread. I can only assume this is caused by the server issues you referenced.

Yes MD is having a issue with their API which FMD uses to do its updating from. If you load a manga chapters via api url its not showing up anything uploaded in last 2-3 days since they had the couple days of down time. So if you want to look then pick what ever manga updated last day or 2, and from url MD/title/<ID#>/.  You used the ID in this API url, https://api.mangadex.org/v2/manga/<ID#>/chapters (i used firefox cause it phases everything in to a pretty easy to sort json page. You can see it doesn't show newest chapter from last 1 or 2 days there. So not really worth doing any update to MD until its fixed.

**Comment by noering** [comment]
Me too, many chapters on new titles do not appear.
Hopefully MD can fix it soon.

**Comment by Qizmo** [comment]
Oh! So this is common problem. I thought I'm the only one who can't download new chapters. ^^

**Comment by Slasar41** [comment]
I decided to revert the module to use the previous API v2 link for now.
Issues like the latest chapter not showing up or some chapters can't be downloaded should be fine now. https://github.com/dazedcat19/FMD2/commit/909fe00dac3dfc033178a12cdb218fc67b53fb8d
If the API server has been fixed, I'll change it back.

**Comment by frerouche** [comment]
But this was about a different issue. What causes the checkforfinish error?
