### ISSUE TITLE
[bug-website module] Random website error download chapter

### ISSUE THREAD

**Issue by mamon4444** [dazedcat19/FMD2#312]
**Prerequisite**
- [ Y ] I'm using the latest version.
- [ Y ] All website modules are up to date.

- [ Y ] This is not a temporary server issue.

**System information**
Your operating system.
I7 8700K, 1080Ti, 16gb ram, ssd 860evo, msi gaming 5 z370 mainboard. Window 10 updated.

**Describe the bug**
So when I chose any random website (I usually use Mangadex, manganelo, mangaeden, blogtruyen) to download a random manga that has a lot of chapters, sometimes some of the chapters will not be downloaded and it will skip that chapter. 

For Example: Hatsukoi limited in mangaEden has 32 chapters and I will get some random chapter like 1 or 2 will be skip, it still created folder of the chapter but nothing will be downloaded, it will skip to chatper 3 and move all untill all chapters are downloaded then it will circle back to chapter 1 and try, and after a certain retried (as set in the setting) it will be marked as fail.

And will not be successful download even if i restart the soft or update the mangalist. This is random to the manga, I think anysite I visit has this problem, but not the same manga.

**Additional context**
I have got it from the very old version until now. Rarely download a complete manga without having a few chatpers got this error. Then I have to switch to another website to download those error chapters.  That's why I jump around from MangaDex to Mangaeden and Manganelo

**Log**
Attach your log file containing the issue if available. Also attach the page source if you can. It will help us solve the issue faster. You can get the page source by opening the particular chapter you're unable to download from your browser with right-click > view page source.

**Comment by Slasar41** [comment]
- MangaEden: You need an account to be able to read Hatsukoi Limited. Since FMD doesn't have account support for MangaEden, you must use a workaround. Here's how to do it: https://github.com/dazedcat19/FMD2/issues/187#issuecomment-736808964. You must already login before doing a workaround.
- MangaNelo: Please provide a manga link example.
- MangaDex: Recently there's a problem on the API side of MangaDex, should be fine now.
- BlogTruyen: Should be fixed after modules update.
