### ISSUE TITLE
[bug-website module] Issue With MerakiScans

### ISSUE THREAD

**Issue by Keyeson** [dazedcat19/FMD2#401]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Linux and Windows 10

**Describe the bug**
Experienced an issue with MerakiScans site/module where on The Last Human it will download the wrong chapter for certain chapters. Have only had this issue for two specific chapters so far. If you try to download what is listed in FMD as 307 - Ch. 302 it will download chapter 30 instead of chapter 302 and the other is 297 - Ch. 292 where it downloads chapter 29 instead. It did not do it anywhere earlier in the entire time I have had it followed.

**Additional context**
This issue seems to be with the newer versions of FMD/modules because I just tried with FMD1 with old modules and it seems to work just fine. Rather odd issue to say the least want to say I may of seen some other modules with similar behaviour of downloading the wrong chapters, but I didn't think much of it at the time so I can't say 100% for sure on that. It looks like 287- Ch. 282 did not have the issue when it was downloaded so the regression was introduced sometime after November 22nd since when I try to download it now it downloads chapter 28.

**Comment by GDXN** [comment]
I can confirm the problem and the problem is related to the line in the lua script:
`46 		local chapter = Trim(GetBetween("var viewschapter =", ";", s):gsub('"', ''))`

as I changing it to
`46 		local chapter = GetBetween("var viewschapter =", ";", s):gsub('"', '')`

and it appears to fix the issue for at least the 10 chapters on witch I tried it.

For me the problem lies in some change and is related to the implementation of "Trim" as this issue was not pressent originally .

Edit - I can confirm that it worked on 2021-03-08 as it is the download date the last chapter that I had donwloaded from MerakiScans until it failed today.
