### ISSUE TITLE
[bug] Updating manga list will freeze the application

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#43]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 2004 64-bit

**Describe the bug**
I want to update a manga list, in this case MangaNelo. So I update and leave it.
When I'm come back checking the result, FMD already freeze.

**To Reproduce**
1. Go to Manga Info tab
2. Select MangaNelo
3. Choose `Update manga list`
4. Leave it

**Expected behavior**
Manga list will finish updating.

**Screenshots**
![image](https://user-images.githubusercontent.com/28888646/86176353-02159200-bb4f-11ea-8a01-cf9eb1bd336a.png)
![image](https://user-images.githubusercontent.com/28888646/86176360-03df5580-bb4f-11ea-8caa-e86a9f1dbab8.png)

**Comment by dazedcat19** [comment]
There's no log? It's immediately froze over or after successfully got something done. what was the last status?(get new manga list/get info for individual manga)
I need to reproduce it quickly. Wasting hours just to reproduce a single bug is such a pain. And I need to reproduce it numerous times to find the bug in codes.

**Comment by dazedcat19** [comment]
I can't reproduce it. I able to finish updating manganelo list without any issue. 

Please elaborate more. the website you're trying to update(can be multiple websites at one go). the number of threads. website settings if any. or maybe it's your custom lua module.

**Comment by Slasar41** [comment]
The number of threads are 10.
Also happened for MangaKakalot.
I just tried it again after updated the module, here's the log: 
[fmd.log](https://github.com/dazedcat19/FMD2/files/4862089/fmd.log)

**Comment by dazedcat19** [comment]
I really unable to reproduce it.
That access violation also looks suspicious. Dunno where that happens.
How about other websites?

**Comment by Slasar41** [comment]
I try with KissManga and lowering the number of threads to 3.
Its get stuck after sometime but no freezing and with a different error now: `02.54.02.285 LUA>DoGetInfo()Access violation`
![SE5vTi96Ew](https://user-images.githubusercontent.com/28888646/86406588-9877be00-bcdd-11ea-90ff-05848a36dcf6.gif)

Edit
When I want to exit like usually, now FMD freeze.
![image](https://user-images.githubusercontent.com/28888646/86410121-6ae24300-bce4-11ea-89b1-00278736ab2d.png)

**Comment by dazedcat19** [comment]
Freeze usually if trapped in loop.
DoGetInfo protected by try except. so, it shouldn't break the loop. and there's nothing special in tupdatethread.getinfo(). the loop should continue. 
access violation happens usually when trying to access unassigned object. looking at lua>dogetinfo the only object is HTTP and MangaInfo. Which should be alive entire time. Because now we're in loop.

Does it only happens after 2.0.15?
I did change the updatelist manager. Previously every getname/getinfo create a new separate thread. now we use existing thread and running it in loop.
The only thing I can think of is GetLuaWebsiteModuleHandler is failed to load the lua chunk. thus return nil. But that's very unlikely since it should return the same previous luahandler. If it fails it should fails from the start.
If you can compile with build mode "Win32 Debug" you can catch more information.
Maybe change the logger.senderror to logger.sendexception to catch the backtrace. thus we can know where the access violation happens.

**Comment by dazedcat19** [comment]
You can try this:

[fmd_i386-win32.7z.zip](https://github.com/dazedcat19/FMD2/files/4869207/fmd_i386-win32.7z.zip)

**Comment by Slasar41** [comment]
I think it's good now. I can finish updating MangaNelo and MangaKakalot database.
Tried back with the latest public FMD I get access violation again.

Could you make a list of all supported websites and maybe make a wiki about it?
Also a list for websites that doesn't have database files so we can add it.

**Comment by dazedcat19** [comment]
Doesn't really found the bug tho.
Shipping a release with debug info is a good thing. But with debug it slowing down a bit. and the size of debug info is quite big. Even when excluding external source codes, it still register all the pointer to it.

You can dump all loaded modules while running fmd with `fmd.exe --dump_loaded_modules` (this should be `--dump-loaded-modules` for the next release). I'm too lazy to even write the changelog.
There's also should be a wiki about fmd's lua api to develop a module.

**Comment by Slasar41** [comment]
As I remember, FMD include a fmd.dbg file until v0.9.158.0.
I just tried again updating MangaKakalot manga list, and it's get stuck like in the first screenshot (The texts are missing) but not freezing. When I take a look at the log it's empty, no error about access violation.
I force close the application and redid updating the manga list and now it's finished without any issue.
So maybe it's a website problem?

Great, thanks.
Now I need to know which that still doesn't have manga list.

**Comment by dazedcat19** [comment]
You can try to mess around the lua module. accessing nil value etc. If that causing the updatelist to be trapped in loop. The easier maybe to debug fmd from lazarus debugger. so when freeze happens you can pause know exactly where it happens.

**Comment by dazedcat19** [comment]
can you monitor the memory consumption. I notice really big memory usage, to GB for getnameandlink. there's no memory leaks though. maybe out of memory is the real issue.

**Comment by Slasar41** [comment]
I can't debug.
Could you update KissManga from scratch on your end?
I'm still getting error:
`03.03.14.488 ERROR: LUA>DoGetInfo("KissManga.lua")>Access violation`
`03.03.14.489 ERROR: TUpdateListThread.GetNamesAndLinks()>ERROR Access violation`
Then it'll freeze.
Already updated to 2.0.17.0

**Comment by dazedcat19** [comment]
You should compile it with debug info line number on. dwarf3 I think quite stable with fpc trunk `-gw3
-gl`.

**Comment by dazedcat19** [comment]
can you take a note of the memory usage when it's running? since the it will run on the same state for a lot of time. there's a possibility of out of memory situation. if not in the main host. maybe in the lua heap.

**Comment by Slasar41** [comment]
Sorry, I can't compile it.

I can't reproduce the issue if the threads are set to 3 with version 2.0.17.0 and 2.0.18.0 now.
But if I set the threads to 10, the issue still happening.
The issue is still happened even with the threads are set to 3 before.
And memory usage seems normal, ~35MB when updating manga list with 3 threads.

**Comment by dazedcat19** [comment]
Is it always in getinfo? or also in getnameandlink?
I previously suspect because the lua state run too many in circle, thus the lua's gc wasn't executed. the memory usage can easily reach GBs after thousands of execution. Mainly the CreateXQuery that consume too much memory. So I run collectgarbage after period of times. And it did eliminate the high memory usage. The weird part is the high memory usage only happened with 1 threads, and some other odd number like 7 and 11, but not always. OOM situation can cause access violation. but, lua never reported that which confuse me.

**Comment by Slasar41** [comment]
The errors always both `DoGetInfo` and `GetNamesAndLinks`.
Can you update KissManga with 10 threads or more?
If you can maybe something is wrong with my system, I can update KissManga manga list successfully even with 30 threads before.
Or maybe KissManga now has some protection that can cause FMD to freeze.

**Comment by dazedcat19** [comment]
Actually, I kinda found where the problem is. It's on the sqlite3 database. Because sqlite3 is not thread safe. So, accessing them should be in synchronize.
FMD1 should also suffer from this bugs. Dunno why I never encountered that before. Maybe because the critical section and the delay when creating the thread itself was slow enough to not causing the race condition. But, I think that just being lucky. The bug should appear sometimes, with a lot of threads and faster clockspeed, the possibility getting higher.

**Comment by dazedcat19** [comment]
try this:

[fmd_i386-win32.7z.zip](https://github.com/dazedcat19/FMD2/files/4900223/fmd_i386-win32.7z.zip)

**Comment by Slasar41** [comment]
Tested and it can handle even with 30 threads now, thanks!

Sometimes cloudflare will need the users to solve hcapctha, does a solver like [this](https://github.com/JimmyLaurent/hcaptcha-solver) can auto solve it and be included in FMD?

**Comment by dazedcat19** [comment]
That is a nodejs module. It need nodejs or maybe require more modules. Hakuneko is so big because it use nodejs and a lot of modules. From my test it was as heavy as opening a browser.

I actually looking forward to a webdriver to open a browser and wait for it for the cookies.
But, because there's no such implementation in pascal like selenium. Writing from scratch will take times.

**Comment by Slasar41** [comment]
Okay, waiting for the implementation.
Someone already did the [script](https://github.com/Inareous/FMD-Kissmanga-Helpers) in python for FMD.
