### ISSUE TITLE
[bug-website module] MangaRockTeam

### ISSUE THREAD

**Issue by Slasar41** [dazedcat19/FMD2#59]
**Prerequisite**
- [x] I'm using the latest version.
- [x] All website modules are up to date.

- [x] This is not temporary server issue.

**System information**
Windows 10 2004 64-bit

**Describe the bug**
Manga Info and chapter list didn't appear.
Example: https://mangarockteam.com/manga/apotheosis/

**Log**
There's no error log.
[view-source_https___mangarockteam.com_manga_apotheosis_.txt](https://github.com/dazedcat19/FMD2/files/4906482/view-source_https___mangarockteam.com_manga_apotheosis_.txt)

**Comment by dazedcat19** [comment]
It's works just fine here. Download also working fine.
when comparing the source you should get the source of what fmd got. not from the browser. browser may change parts of the html source to be readable, or execute some lazy script that change preloaded source. beside the server might send different file for each request.
`HTTP.Document.SaveToFile("tempfile.html")`
When developing a module I usually using the downloaded file instead of new request.
instead of `HTTP.GET("url")` I just load the downloaded file with `HTTP.Document.LoadFromFile("tempfile.html")`. I also always use `--lua-dofile` while developing, So I can edit the lua file at runtime and execute it right away without restarting fmd.

![img-20200712-102318](https://user-images.githubusercontent.com/59296763/87237514-d9807880-c429-11ea-895a-592a17c97214.jpg)

**Comment by Slasar41** [comment]
I just noticed to access the website I need to solve the cloudflare captcha so I've to copy the cookies and it's works fine again.
Weird, I don't have to solve the captcha so I just assume it's a website issue before.
> when comparing the source you should get the source of what fmd got. not from the browser. browser may change parts of the html source to be readable, or execute some lazy script that change preloaded source. beside the server might send different file for each request.
> `HTTP.Document.SaveToFile("tempfile.html")`

I see, I'll do that next time.
> When developing a module I usually using the downloaded file instead of new request.
> instead of `HTTP.GET("url")` I just load the downloaded file with `HTTP.Document.LoadFromFile("tempfile.html")`. I also always use `--lua-dofile` while developing, So I can edit the lua file at runtime and execute it right away without restarting fmd.

I never knew this. I'm frustrated when I've to restart FMD everytime I made an edit to the lua file.
This is a good information for wiki if you want to make it.

**Comment by dazedcat19** [comment]
You can write a wiki if you wanted. I'm too lazy to do that. There's should be a wiki about all the provided lua api.

`--lua-dofile` will not execute the `Init()` function. So you have to write everything it need before launching fmd. and make sure it can run without any error (typed error, run error).
`fmd.exe --lua-dofile`. better make a shortcut with this parameter.
don't forget to enable the log. then you can monitor the log with tail, `tail.exe -f -n 20 fmd.log`. I prefer this way. any error after you modify the lua source should be printed in the log file. you can fix it right away and try it again without the need to restart fmd. it should load the chunk from the file. there's some exception like in running download or update list. you have to stop it first.

`--lua-dofile` isn't suitable for normal run. because it's always load the chunk from a file it will cause heavy IO.
FMD1 suffer from heavy IO with a module with template even in normal run. Because it's not intercepting module load `require "template"`. also all the module that use `require`.
FMD2 overall has better memory management. You can compare it only by the visual in task manager.
All modules isn't pre-cached like FMD1. Only the used modules will be cached. triggered by module use. so does the lua module (`require "module"`). starting a download, open a mangainfo. checking favorite etc.
FMD2 has a lot of improvement and bug fixes. Better download manager, favorites manager, prevent standby/sleep while download running, faster startup. Fixed save the data when restart/log off (FMD1 doesn't have this, so if we restart or log off without closing fmd. it will not store the settings/databases.) and more.
It should be in the changelog. But I'm too lazy. you can help rewriting the changelog by reading the commit messages.
