### ISSUE TITLE
[ASK] Does asurascans have any traffic limitations?

### ISSUE THREAD

**Issue by spamtaztik** [dazedcat19/FMD2#597]
I tried updating my titles for asurascans today, but all of them came out as 403 ("forbidden" or something). I can't even open the site from chrome. After a while access to the site is working again, so I'm assuming it's a temporary ban or something. 

My question: does the site limit my traffic? Granted, I don't put any max task/threadpertask/connection limit in FMD for it because I've never really downloaded from them before. If so, what's a good FMD setting so I won't get "banned" like this again in the future? Set max task/threadpertask/connection limit and updatelist blah blah to 1?

**Comment by Slasar41** [comment]
How many connection numbers you put right now?

**Comment by ahmadi3d** [comment]
My experience with asurascans : 
1- You shouldn't try opening multiple pages at once, meaning you should put a limit for connection number to avoid 403.
2- you can apply cookie solution
3-Wehther you do apply cookie solution or not, sometimes it just doesn't download and sometimes it does!, it seems that you can at least download once or twice a week from the site, i know this because my downloader is always open and I've been doing this for months.

**Comment by spamtaztik** [comment]
@Slasar41 None. Like I said, I never downloaded from them before. This is my first time trying.

@ahmadi3d I'll try that. Thanks.

UPDATE: It -seems- that setting everything to 1 makes it possible to circumvent the 403 limitation. So that's the solution, I guess? Thanks for answering.
