### ISSUE TITLE
Not Able to use the program on window 11.

### ISSUE THREAD

**Issue by VijayThagriya** [dazedcat19/FMD2#678]
simple question , not able to open the program even after changing compatibility. is there any way to make it work.

**Comment by Slasar41** [comment]
Works fine on my end and there's no need to change the compatibility mode.
Here's a screenshot example I took weeks ago.
![image](https://cdn.discordapp.com/attachments/564048726918955008/868208743291166760/unknown.png)

**Comment by joeb2000** [comment]
Works fine on my windows 11 system and my wife's windows 11 system as well.

That being said, we had to install windows 11 in a round about way disabling the TPM and SecureBoot checks. But have had zero problems with it. So if you have a regular version maybe one of those things is causing the issue.

Edit: I had a thought afterwords. Try right clicking on the FMD.exe and pulling up the properties. It is possible the computer flagged it as being from another system and has it blocked. I had a couple of other programs do that to my system since they did not require installing and I just ran them. If that is the issue you should just have to check the box to unblock it.
![Capture](https://user-images.githubusercontent.com/65504709/129657341-2f20fa6d-abee-4d6f-9447-77f51459c73a.PNG)
.

**Comment by VijayThagriya** [comment]
> Works fine on my windows 11 system and my wife's windows 11 system as well.
> 
> That being said, we had to install windows 11 in a round about way disabling the TPM and SecureBoot checks. But have had zero problems with it. So if you have a regular version maybe one of those things is causing the issue.
> 
> Edit: I had a thought afterwords. Try right clicking on the FMD.exe and pulling up the properties. It is possible the computer flagged it as being from another system and has it blocked. I had a couple of other programs do that to my system since they did not require installing and I just ran them. If that is the issue you should just have to check the box to unblock it.
> ![Capture](https://user-images.githubusercontent.com/65504709/129657341-2f20fa6d-abee-4d6f-9447-77f51459c73a.PNG)
> .

Thanks For Reply .
Fmd.exe is not blocked. Downloaded new one tried again. it shows same error of execution of program.
here are screenshotof error. my windows build is 21HR Pro verison.
![Screenshot (1)](https://user-images.githubusercontent.com/48792526/129669661-60d4fbde-dac9-4089-b3e7-976ed7e51260.png)
![Screenshot (3)](https://user-images.githubusercontent.com/48792526/129669664-b079c0bc-d4d6-410d-a639-06c5882e90c5.png)

**Comment by Slasar41** [comment]
I see the issue.
Download this file and replace it to FMD folder: https://github.com/dazedcat19/FMD2/blob/master/dist/x86_64-win64/libwebp.dll

**Comment by VijayThagriya** [comment]
> I see the issue.
> Download this file and replace it to FMD folder: https://github.com/dazedcat19/FMD2/blob/master/dist/x86_64-win64/libwebp.dll

Thanks for the file . Problem Fixed.
