### ISSUE TITLE
[bug]mangapark cannot view info and download

### ISSUE THREAD

**Issue by kazenoade** [dazedcat19/FMD2#75]
Problem with mangapark (again) maybe. 
<img width="939" alt="fmdbug" src="https://user-images.githubusercontent.com/59524272/88243178-bcfdff00-ccb9-11ea-8a9b-942701fa379d.png">

**Comment by Qizmo** [comment]
Same for me. And those in Favorites also have their name with red background

**Comment by Slasar41** [comment]
Because the cloudflare's captcha need to be solved and FMD doesn't support auto solving it yet, you've to do cookies workaround.

**Comment by AltPlus248** [comment]
Sorry if this has been answered before but I couldn't find a guide for the CF work around for MangaPark's cookies. I tried turning enable to true, setting every variable to 1, adding the UserAgent and putting the cookies
"__cfduid=(cookie);
cf_clearance=(cookie)"
and
"__cfduid=(cookie);
cf_clearance=(cookie);
cf_chl_1=(cookie)"
and put them in both the MangaPark and MangaParkNet section since I'm not sure which one is the one I need (I don't use the FMD's search function, I just copy and paste the links directly from https://mangapark.net/). But it still isn't connecting so I'm guessing I don't have all of the cookies I need in the right order.

**Comment by Slasar41** [comment]
@AltPlus248 You need to copy all the cookies and paste it without separating it with a new line.
![image](https://user-images.githubusercontent.com/28888646/88418372-a8328000-ce0d-11ea-99b6-15adabcf3a85.png)
The MangaPark module's url is https://mangapark.me which is redirected to https://mangapark.net and that's the url for MangaParkNet module.
So MangaPark doesn't work anymore, use MangaParkNet.

**Comment by AltPlus248** [comment]
Thank you, It's working now.
