### ISSUE TITLE
[feature request] Better Error Handling When downloading / Check downloaded chapters and retry to download the corrupted/missing files 

### ISSUE THREAD

**Issue by TehBotolSosro** [dazedcat19/FMD2#94]
**Is your feature request related to a problem? Please describe.**
Hello,

When i download from a site say mangadex or any other site
sometime FMD miss a few page/image in a chapter, example it have 19 page/image, the file name 01 - 19 and it was missing page 12, and 17 (the file is missing, so the file olny have page 1-11,13-16,18-19), the status of the task is always completed rather than failed task, it seem it's because either my connection is slowed down (perhaps because i'm downloading other stuff in torrent) or perhaps the connection to the site is having issue or the site have too many user so it's crawling,  and i need to manually check the downloaded file so i can restart it manually so it can redownload the missing page, and it's harder to check when i download many chapter at once

**Describe the solution you'd like**

Perhaps fmd should have check all the page are properly downloaded before it complete, or maybe count the total page/image need to be downloaded and count it after it's downloaded and see if it's missing any pages and automatically retry the task,

**Describe alternatives you've considered**
or maybe it could do a hash check compare so it properly downloading all the pages. this will help also with corrupted download (but i haven't get any corrupted download it just the page are not downloaded)

**Additional context**
these request has been requested a year ago in fmd1, so for more info you can see https://github.com/fmd-project-team/FMD/issues/25

thanks

**Comment by dazedcat19** [comment]
fmd does check the finished download by the existence of its files. you can look at the `udownloadmanager.pas`
there's multiple check running before set the status complete. after download it check the stream header. if it's known image file then it will save it to disk otherwise marked as failed. after writing to disk it will check the existence of the file. then mark it as downloaded "D". after chapter complete it check again the existence of all files, it will mark "W" for missing files. then count the "W". if there's missing files it will mark the chapter as failed. after the task finished it will check the failed chapters. if there's any then it set the status as failed. when restarting the download, regardless of its status, it also will check the files, so it can skip the existing file and redownload the missing files. before compressing the chapters, it also does multiple check. so there's actually a lot of check before deciding the status as failed/finish.
comparing the hash check to what? I don't see any website that put the hash infomation for each images.
some of the possibility was the website module not collecting the image list properly. or some antivirus program remove the files right after it set as finish/when compressing. some heuristic antivirus does this for some reason. maybe it decide the program as suspicious when constantly write a lot of files and removing it. make sure to put fmd and download folder into exception.
also try to use the 32bit version. I remembered there's a bug in fpc compiler that causing the compressor to fail but without notice. not exactly but something related to https://bugs.freepascal.org/view.php?id=37305
I put various workaround to fix it and never encounter it again. there's also some seh problem with win64.

if it was a real bug then I need a reproducible steps to investigate.
